source "http://rubygems.org"

gem "rack", "1.3.5"
gem "sinatra"
gem "rack-flash"
gem "unicorn"
gem "god"
gem "rake"

gem "mysql2"
gem "data_mapper"
gem "dm-mysql-adapter"
gem "dm-adjust"
gem "dm-aggregates"
gem "redis"

gem "statistics2"
gem "bcrypt-ruby"
gem "ruby-mp3info"
gem "httparty"

gem "haml"
gem "sass"
gem "therubyracer"
gem "coffee-script"
gem "barista"