source "http://rubygems.org"

gem "rack", "1.3.5"
gem "sinatra"
gem "rack-flash"
gem "sinatra-redirect-with-flash"
gem "sinatra-cache-assets"
gem "unicorn"

gem "mysql2"
gem "data_mapper"
gem "dm-mysql-adapter"
gem "dm-adjust"
gem "dm-aggregates"

gem "redis"
gem "json"
gem "bcrypt-ruby"
gem "active_support"
gem "ruby-mp3info"
gem "httparty"
gem "packr"
gem "rainpress"
gem "highline"
gem "yaml"

gem "haml"
gem "sass"
gem "therubyracer"
gem "coffee-script"